### ISSUE TITLE
Add support for Unwired's LocationAPI

### ISSUE THREAD

**Issue by gopi-ar** [twang2218/mobile-locator#3]
Hello!

Wondering if you could add support for Unwired Labs' LocationAPI. Unwired is the new maintainer of OpenCelliD as well. Our team doesn't have much NodeJS experience else we'd have sent in a PR.

If you do take this up, the API specs are here: https://unwiredlabs.com/api

Cheers,
Gopi

**Comment by twang2218** [comment]
Thanks for your interest, I just implemented the Unwired Labs Location API in version 0.5.0, you can test it by command `mobile-locator`, if you installed it in global via `npm install mobile-locator -g`.

```bash
$ mobile-locator -e unwiredlabs -a "token:YOUR_API_TOKEN" -c 222,10,10012,39309
{"longitude":8.811392,"latitude":45.640712,"accuracy":908,"address":"Via Sardegna, Madonna in Campagna, Gallarate, VA, Lombardy, 21052, Italy"}
```

**Comment by gopi-ar** [comment]
That's great, thank you! We support multiple cells & WiFis in each request as well, so if you plan on adding that in the future, do let us know!

Closing this thread..
